### ISSUE TITLE
FLT0101

### ISSUE THREAD

**Issue by StefanAlMare** [chilledHamza/VoodooPS2FocalTech#3] opened 2021-10-09 16:11 UTC
Hi! Do you think, you can make this kext work also with FLT0101?
If I need to provide something, please tell me.

**Comment by chilledHamza** [comment] 2021-10-28 20:54
duplicate of #1 

It's possible but i don't have device for testing/development. There is some difference in packet structure of both devices, FLT0101 handles multi-touch differently. So it will require changes to packet parsing code mainly, everything else remains same.

**Closed as completed by chilledHamza** 2021-10-28 20:54 UTC
Labels: duplicate
